---
name: Scaffold Terraform Module
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: 'module path'
        required: true
permissions:
  contents: read
  pull-requests: write
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v1.2.0
        with:
          aqua_version: v1.12.1

      # We recommend using GitHub App Token instead of personal access token,
      # but in this getting started let's use personal access token.
      # - name: Generate token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: suzuki-shunsuke/tfaction/scaffold-module@v0.5.25
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          module_path: ${{ github.event.inputs.module_path }}
